/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface LotteryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "CALLBACK_GAS_LIMIT"
      | "NUMBER_OF_WORDS"
      | "NUMBER_RANGE"
      | "REQUEST_CONFIRMATIONS"
      | "TICKET_PRICE_WEI"
      | "acceptOwnership"
      | "addressToActiveTicketNumber"
      | "buyTicket"
      | "getActiveTicketNumber"
      | "getContractOwner"
      | "getJackpot"
      | "getResults"
      | "jackpot"
      | "nextTicketId"
      | "owner"
      | "rawFulfillRandomWords"
      | "requestIdToTicketId"
      | "s_vrfCoordinator"
      | "setCoordinator"
      | "submitCombination"
      | "tickets"
      | "transferOwnership"
      | "withdrawOperationsBalance"
      | "withdrawOwnerBalance"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CoordinatorSet"
      | "Distribute"
      | "LotteryResults"
      | "OperationsBalanceWithdraw"
      | "OwnerBalanceWithdraw"
      | "OwnershipTransferRequested"
      | "OwnershipTransferred"
      | "PlayerCombinationSubmitted"
      | "RandomNumberGenerated"
      | "RewardClaimed"
      | "TicketPurchased"
      | "WinningCombinationGenerated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "CALLBACK_GAS_LIMIT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "NUMBER_OF_WORDS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "NUMBER_RANGE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REQUEST_CONFIRMATIONS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TICKET_PRICE_WEI",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addressToActiveTicketNumber",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "buyTicket", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getActiveTicketNumber",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getContractOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getJackpot",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getResults",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "jackpot", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "nextTicketId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "rawFulfillRandomWords",
    values: [BigNumberish, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "requestIdToTicketId",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "s_vrfCoordinator",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setCoordinator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitCombination",
    values: [
      BigNumberish,
      [BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "tickets",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawOperationsBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawOwnerBalance",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "CALLBACK_GAS_LIMIT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "NUMBER_OF_WORDS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "NUMBER_RANGE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REQUEST_CONFIRMATIONS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TICKET_PRICE_WEI",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addressToActiveTicketNumber",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "buyTicket", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getActiveTicketNumber",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContractOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getJackpot", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getResults", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "jackpot", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextTicketId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "rawFulfillRandomWords",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestIdToTicketId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "s_vrfCoordinator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCoordinator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitCombination",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tickets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawOperationsBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawOwnerBalance",
    data: BytesLike
  ): Result;
}

export namespace CoordinatorSetEvent {
  export type InputTuple = [vrfCoordinator: AddressLike];
  export type OutputTuple = [vrfCoordinator: string];
  export interface OutputObject {
    vrfCoordinator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DistributeEvent {
  export type InputTuple = [owner: AddressLike, amount: BigNumberish];
  export type OutputTuple = [owner: string, amount: bigint];
  export interface OutputObject {
    owner: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LotteryResultsEvent {
  export type InputTuple = [
    owner: AddressLike,
    ticketNumber: BigNumberish,
    playerCombination: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ],
    winningCombination: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ],
    matchingNumbers: BigNumberish,
    rewardAmount: BigNumberish
  ];
  export type OutputTuple = [
    owner: string,
    ticketNumber: bigint,
    playerCombination: [bigint, bigint, bigint, bigint, bigint],
    winningCombination: [bigint, bigint, bigint, bigint, bigint],
    matchingNumbers: bigint,
    rewardAmount: bigint
  ];
  export interface OutputObject {
    owner: string;
    ticketNumber: bigint;
    playerCombination: [bigint, bigint, bigint, bigint, bigint];
    winningCombination: [bigint, bigint, bigint, bigint, bigint];
    matchingNumbers: bigint;
    rewardAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OperationsBalanceWithdrawEvent {
  export type InputTuple = [owner: AddressLike, amount: BigNumberish];
  export type OutputTuple = [owner: string, amount: bigint];
  export interface OutputObject {
    owner: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnerBalanceWithdrawEvent {
  export type InputTuple = [owner: AddressLike, amount: BigNumberish];
  export type OutputTuple = [owner: string, amount: bigint];
  export interface OutputObject {
    owner: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferRequestedEvent {
  export type InputTuple = [from: AddressLike, to: AddressLike];
  export type OutputTuple = [from: string, to: string];
  export interface OutputObject {
    from: string;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [from: AddressLike, to: AddressLike];
  export type OutputTuple = [from: string, to: string];
  export interface OutputObject {
    from: string;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlayerCombinationSubmittedEvent {
  export type InputTuple = [
    player: AddressLike,
    combination: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ];
  export type OutputTuple = [
    player: string,
    combination: [bigint, bigint, bigint, bigint, bigint]
  ];
  export interface OutputObject {
    player: string;
    combination: [bigint, bigint, bigint, bigint, bigint];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RandomNumberGeneratedEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    ticketNumber: BigNumberish,
    number: BigNumberish
  ];
  export type OutputTuple = [
    requestId: bigint,
    ticketNumber: bigint,
    number: bigint
  ];
  export interface OutputObject {
    requestId: bigint;
    ticketNumber: bigint;
    number: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardClaimedEvent {
  export type InputTuple = [
    player: AddressLike,
    ticketId: BigNumberish,
    amount: BigNumberish
  ];
  export type OutputTuple = [player: string, ticketId: bigint, amount: bigint];
  export interface OutputObject {
    player: string;
    ticketId: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TicketPurchasedEvent {
  export type InputTuple = [player: AddressLike, ticketNumber: BigNumberish];
  export type OutputTuple = [player: string, ticketNumber: bigint];
  export interface OutputObject {
    player: string;
    ticketNumber: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WinningCombinationGeneratedEvent {
  export type InputTuple = [
    ticketNumber: BigNumberish,
    combination: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ];
  export type OutputTuple = [
    ticketNumber: bigint,
    combination: [bigint, bigint, bigint, bigint, bigint]
  ];
  export interface OutputObject {
    ticketNumber: bigint;
    combination: [bigint, bigint, bigint, bigint, bigint];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Lottery extends BaseContract {
  connect(runner?: ContractRunner | null): Lottery;
  waitForDeployment(): Promise<this>;

  interface: LotteryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  CALLBACK_GAS_LIMIT: TypedContractMethod<[], [bigint], "view">;

  NUMBER_OF_WORDS: TypedContractMethod<[], [bigint], "view">;

  NUMBER_RANGE: TypedContractMethod<[], [bigint], "view">;

  REQUEST_CONFIRMATIONS: TypedContractMethod<[], [bigint], "view">;

  TICKET_PRICE_WEI: TypedContractMethod<[], [bigint], "view">;

  acceptOwnership: TypedContractMethod<[], [void], "nonpayable">;

  addressToActiveTicketNumber: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  buyTicket: TypedContractMethod<[], [void], "payable">;

  getActiveTicketNumber: TypedContractMethod<
    [walletAddress: AddressLike],
    [bigint],
    "view"
  >;

  getContractOwner: TypedContractMethod<[], [string], "view">;

  getJackpot: TypedContractMethod<[], [bigint], "view">;

  getResults: TypedContractMethod<
    [ticketId: BigNumberish],
    [void],
    "nonpayable"
  >;

  jackpot: TypedContractMethod<[], [bigint], "view">;

  nextTicketId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  rawFulfillRandomWords: TypedContractMethod<
    [requestId: BigNumberish, randomWords: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  requestIdToTicketId: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  s_vrfCoordinator: TypedContractMethod<[], [string], "view">;

  setCoordinator: TypedContractMethod<
    [_vrfCoordinator: AddressLike],
    [void],
    "nonpayable"
  >;

  submitCombination: TypedContractMethod<
    [
      ticketId: BigNumberish,
      playerCombination: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ]
    ],
    [void],
    "nonpayable"
  >;

  tickets: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint, boolean, boolean, boolean] & {
        id: bigint;
        owner: string;
        purchaseTimestamp: bigint;
        randomWord: bigint;
        isRewardClaimed: boolean;
        playerCombinationSubmitted: boolean;
        winningCombinationGenerated: boolean;
      }
    ],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [to: AddressLike],
    [void],
    "nonpayable"
  >;

  withdrawOperationsBalance: TypedContractMethod<[], [void], "payable">;

  withdrawOwnerBalance: TypedContractMethod<[], [void], "payable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "CALLBACK_GAS_LIMIT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "NUMBER_OF_WORDS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "NUMBER_RANGE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "REQUEST_CONFIRMATIONS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TICKET_PRICE_WEI"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "acceptOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addressToActiveTicketNumber"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "buyTicket"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "getActiveTicketNumber"
  ): TypedContractMethod<[walletAddress: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getContractOwner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getJackpot"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getResults"
  ): TypedContractMethod<[ticketId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "jackpot"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextTicketId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "rawFulfillRandomWords"
  ): TypedContractMethod<
    [requestId: BigNumberish, randomWords: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestIdToTicketId"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "s_vrfCoordinator"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setCoordinator"
  ): TypedContractMethod<[_vrfCoordinator: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitCombination"
  ): TypedContractMethod<
    [
      ticketId: BigNumberish,
      playerCombination: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "tickets"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint, boolean, boolean, boolean] & {
        id: bigint;
        owner: string;
        purchaseTimestamp: bigint;
        randomWord: bigint;
        isRewardClaimed: boolean;
        playerCombinationSubmitted: boolean;
        winningCombinationGenerated: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[to: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawOperationsBalance"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "withdrawOwnerBalance"
  ): TypedContractMethod<[], [void], "payable">;

  getEvent(
    key: "CoordinatorSet"
  ): TypedContractEvent<
    CoordinatorSetEvent.InputTuple,
    CoordinatorSetEvent.OutputTuple,
    CoordinatorSetEvent.OutputObject
  >;
  getEvent(
    key: "Distribute"
  ): TypedContractEvent<
    DistributeEvent.InputTuple,
    DistributeEvent.OutputTuple,
    DistributeEvent.OutputObject
  >;
  getEvent(
    key: "LotteryResults"
  ): TypedContractEvent<
    LotteryResultsEvent.InputTuple,
    LotteryResultsEvent.OutputTuple,
    LotteryResultsEvent.OutputObject
  >;
  getEvent(
    key: "OperationsBalanceWithdraw"
  ): TypedContractEvent<
    OperationsBalanceWithdrawEvent.InputTuple,
    OperationsBalanceWithdrawEvent.OutputTuple,
    OperationsBalanceWithdrawEvent.OutputObject
  >;
  getEvent(
    key: "OwnerBalanceWithdraw"
  ): TypedContractEvent<
    OwnerBalanceWithdrawEvent.InputTuple,
    OwnerBalanceWithdrawEvent.OutputTuple,
    OwnerBalanceWithdrawEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferRequested"
  ): TypedContractEvent<
    OwnershipTransferRequestedEvent.InputTuple,
    OwnershipTransferRequestedEvent.OutputTuple,
    OwnershipTransferRequestedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PlayerCombinationSubmitted"
  ): TypedContractEvent<
    PlayerCombinationSubmittedEvent.InputTuple,
    PlayerCombinationSubmittedEvent.OutputTuple,
    PlayerCombinationSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "RandomNumberGenerated"
  ): TypedContractEvent<
    RandomNumberGeneratedEvent.InputTuple,
    RandomNumberGeneratedEvent.OutputTuple,
    RandomNumberGeneratedEvent.OutputObject
  >;
  getEvent(
    key: "RewardClaimed"
  ): TypedContractEvent<
    RewardClaimedEvent.InputTuple,
    RewardClaimedEvent.OutputTuple,
    RewardClaimedEvent.OutputObject
  >;
  getEvent(
    key: "TicketPurchased"
  ): TypedContractEvent<
    TicketPurchasedEvent.InputTuple,
    TicketPurchasedEvent.OutputTuple,
    TicketPurchasedEvent.OutputObject
  >;
  getEvent(
    key: "WinningCombinationGenerated"
  ): TypedContractEvent<
    WinningCombinationGeneratedEvent.InputTuple,
    WinningCombinationGeneratedEvent.OutputTuple,
    WinningCombinationGeneratedEvent.OutputObject
  >;

  filters: {
    "CoordinatorSet(address)": TypedContractEvent<
      CoordinatorSetEvent.InputTuple,
      CoordinatorSetEvent.OutputTuple,
      CoordinatorSetEvent.OutputObject
    >;
    CoordinatorSet: TypedContractEvent<
      CoordinatorSetEvent.InputTuple,
      CoordinatorSetEvent.OutputTuple,
      CoordinatorSetEvent.OutputObject
    >;

    "Distribute(address,uint256)": TypedContractEvent<
      DistributeEvent.InputTuple,
      DistributeEvent.OutputTuple,
      DistributeEvent.OutputObject
    >;
    Distribute: TypedContractEvent<
      DistributeEvent.InputTuple,
      DistributeEvent.OutputTuple,
      DistributeEvent.OutputObject
    >;

    "LotteryResults(address,uint256,uint256[5],uint256[5],uint8,uint256)": TypedContractEvent<
      LotteryResultsEvent.InputTuple,
      LotteryResultsEvent.OutputTuple,
      LotteryResultsEvent.OutputObject
    >;
    LotteryResults: TypedContractEvent<
      LotteryResultsEvent.InputTuple,
      LotteryResultsEvent.OutputTuple,
      LotteryResultsEvent.OutputObject
    >;

    "OperationsBalanceWithdraw(address,uint256)": TypedContractEvent<
      OperationsBalanceWithdrawEvent.InputTuple,
      OperationsBalanceWithdrawEvent.OutputTuple,
      OperationsBalanceWithdrawEvent.OutputObject
    >;
    OperationsBalanceWithdraw: TypedContractEvent<
      OperationsBalanceWithdrawEvent.InputTuple,
      OperationsBalanceWithdrawEvent.OutputTuple,
      OperationsBalanceWithdrawEvent.OutputObject
    >;

    "OwnerBalanceWithdraw(address,uint256)": TypedContractEvent<
      OwnerBalanceWithdrawEvent.InputTuple,
      OwnerBalanceWithdrawEvent.OutputTuple,
      OwnerBalanceWithdrawEvent.OutputObject
    >;
    OwnerBalanceWithdraw: TypedContractEvent<
      OwnerBalanceWithdrawEvent.InputTuple,
      OwnerBalanceWithdrawEvent.OutputTuple,
      OwnerBalanceWithdrawEvent.OutputObject
    >;

    "OwnershipTransferRequested(address,address)": TypedContractEvent<
      OwnershipTransferRequestedEvent.InputTuple,
      OwnershipTransferRequestedEvent.OutputTuple,
      OwnershipTransferRequestedEvent.OutputObject
    >;
    OwnershipTransferRequested: TypedContractEvent<
      OwnershipTransferRequestedEvent.InputTuple,
      OwnershipTransferRequestedEvent.OutputTuple,
      OwnershipTransferRequestedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PlayerCombinationSubmitted(address,uint256[5])": TypedContractEvent<
      PlayerCombinationSubmittedEvent.InputTuple,
      PlayerCombinationSubmittedEvent.OutputTuple,
      PlayerCombinationSubmittedEvent.OutputObject
    >;
    PlayerCombinationSubmitted: TypedContractEvent<
      PlayerCombinationSubmittedEvent.InputTuple,
      PlayerCombinationSubmittedEvent.OutputTuple,
      PlayerCombinationSubmittedEvent.OutputObject
    >;

    "RandomNumberGenerated(uint256,uint256,uint256)": TypedContractEvent<
      RandomNumberGeneratedEvent.InputTuple,
      RandomNumberGeneratedEvent.OutputTuple,
      RandomNumberGeneratedEvent.OutputObject
    >;
    RandomNumberGenerated: TypedContractEvent<
      RandomNumberGeneratedEvent.InputTuple,
      RandomNumberGeneratedEvent.OutputTuple,
      RandomNumberGeneratedEvent.OutputObject
    >;

    "RewardClaimed(address,uint256,uint256)": TypedContractEvent<
      RewardClaimedEvent.InputTuple,
      RewardClaimedEvent.OutputTuple,
      RewardClaimedEvent.OutputObject
    >;
    RewardClaimed: TypedContractEvent<
      RewardClaimedEvent.InputTuple,
      RewardClaimedEvent.OutputTuple,
      RewardClaimedEvent.OutputObject
    >;

    "TicketPurchased(address,uint256)": TypedContractEvent<
      TicketPurchasedEvent.InputTuple,
      TicketPurchasedEvent.OutputTuple,
      TicketPurchasedEvent.OutputObject
    >;
    TicketPurchased: TypedContractEvent<
      TicketPurchasedEvent.InputTuple,
      TicketPurchasedEvent.OutputTuple,
      TicketPurchasedEvent.OutputObject
    >;

    "WinningCombinationGenerated(uint256,uint256[5])": TypedContractEvent<
      WinningCombinationGeneratedEvent.InputTuple,
      WinningCombinationGeneratedEvent.OutputTuple,
      WinningCombinationGeneratedEvent.OutputObject
    >;
    WinningCombinationGenerated: TypedContractEvent<
      WinningCombinationGeneratedEvent.InputTuple,
      WinningCombinationGeneratedEvent.OutputTuple,
      WinningCombinationGeneratedEvent.OutputObject
    >;
  };
}
